/* -*- c++ -*- */
#ifndef PROTOMOL_H
#define PROTOMOL_H

/*
 * Include file for global configuration flags for ProtoMol.
 *
 * For Windows you may extend/change "protomol_config_windows.h",
 * "protomol_config.h" is generated by configure.
 */


#ifndef WIN32
#include "protomol_config.h"
#else
#include "protomol_config_windows.h"
#endif

#endif
