default: performance clean

performance: performance.tex

	pdflatex performance.tex
	pdflatex performance.tex


clean: 
	rm -f *.dvi *.aux *.log *.blg *~

realclean: clean
	rm -f performance.pdf performance.ps *.bbl
