default: idl clean

idl: integratorDefinitionLanguage.tex

	pdflatex integratorDefinitionLanguage.tex
	pdflatex integratorDefinitionLanguage.tex


clean: 
	rm -f *.dvi *.aux *.log *.blg *~

realclean: clean
	rm -f integratorDefinitionLanguage.pdf integratorDefinitionLanguage.ps *.bbl
